fuckery(1) [""["fuckery-VERSION"]]

# NAME

fuckery - General unicode tomfoolery.

# SYNOPSIS

*fuckery [style]*

# STYLES

- Strike
- Underline
- BoldSans
- BoldSerif
- ItalicSans
- ItalicSerif
- BoldItalicSans
- BoldItalicSerif
- Double
- Cursive
- Fraktur
- Zalgo 7 (greater numbers have more zalg)

# AUTHORS

Maintained by Dakota Walsh <kota at nilsu.org>.
Up-to-date sources can be found at https://git.sr.ht/~kota/fuckery/
